name: Run Scraper

on:
  schedule:
    - cron: "0 * * * *"   # every hour (UTC)
  workflow_dispatch:       # allow manual trigger from Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add trends.csv
          git commit -m "Update trends.csv" || echo "No changes to commit"
          git push
